/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IdRouteImport } from './routes/$id'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiSetupRouteImport } from './routes/api/setup'
import { Route as ApiRegisterRouteImport } from './routes/api/register'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiMediaIdRouteImport } from './routes/api/media.$id'
import { Route as ApiImageIdRouteImport } from './routes/api/image.$id'

const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupRoute = ApiSetupRouteImport.update({
  id: '/api/setup',
  path: '/api/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterRoute = ApiRegisterRouteImport.update({
  id: '/api/register',
  path: '/api/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageIdRoute = ApiImageIdRouteImport.update({
  id: '/api/image/$id',
  path: '/api/image/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/api/ping': typeof ApiPingRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/setup': typeof ApiSetupRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/version': typeof ApiVersionRoute
  '/api/image/$id': typeof ApiImageIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/api/ping': typeof ApiPingRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/setup': typeof ApiSetupRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/version': typeof ApiVersionRoute
  '/api/image/$id': typeof ApiImageIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/api/ping': typeof ApiPingRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/setup': typeof ApiSetupRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/version': typeof ApiVersionRoute
  '/api/image/$id': typeof ApiImageIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$id'
    | '/api/ping'
    | '/api/register'
    | '/api/setup'
    | '/api/upload'
    | '/api/version'
    | '/api/image/$id'
    | '/api/media/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$id'
    | '/api/ping'
    | '/api/register'
    | '/api/setup'
    | '/api/upload'
    | '/api/version'
    | '/api/image/$id'
    | '/api/media/$id'
  id:
    | '__root__'
    | '/'
    | '/$id'
    | '/api/ping'
    | '/api/register'
    | '/api/setup'
    | '/api/upload'
    | '/api/version'
    | '/api/image/$id'
    | '/api/media/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiRegisterRoute: typeof ApiRegisterRoute
  ApiSetupRoute: typeof ApiSetupRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiVersionRoute: typeof ApiVersionRoute
  ApiImageIdRoute: typeof ApiImageIdRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup': {
      id: '/api/setup'
      path: '/api/setup'
      fullPath: '/api/setup'
      preLoaderRoute: typeof ApiSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register': {
      id: '/api/register'
      path: '/api/register'
      fullPath: '/api/register'
      preLoaderRoute: typeof ApiRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image/$id': {
      id: '/api/image/$id'
      path: '/api/image/$id'
      fullPath: '/api/image/$id'
      preLoaderRoute: typeof ApiImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRoute,
  ApiPingRoute: ApiPingRoute,
  ApiRegisterRoute: ApiRegisterRoute,
  ApiSetupRoute: ApiSetupRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiVersionRoute: ApiVersionRoute,
  ApiImageIdRoute: ApiImageIdRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
